// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.outbound-webhook@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const OUTBOUND_WEBHOOK_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const OUTBOUND_WEBHOOK_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_outbound_webhook { () => { "{\"capability_id\":\"lenso.outbound-webhook@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"enqueue\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_outbound_webhook_client { () => { "{\"capability_id\":\"lenso.outbound-webhook@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_outbound_webhook_client { () => { "{\"capability_id\":\"lenso.outbound-webhook@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const ENQUEUE_OPERATION: &str = "enqueue";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct EnqueueRequest {
    #[serde(rename = "event_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub event_id: String,
    #[serde(rename = "event_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub event_type: String,
    #[serde(rename = "payload")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub payload: std::collections::BTreeMap<String, serde_json::Value>,
}

impl fmt::Debug for EnqueueRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("EnqueueRequest")
            .field("event_id", &self.event_id)
            .field("event_type", &self.event_type)
            .field("payload", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct EnqueueResponse {
    #[serde(rename = "created")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created: bool,
    #[serde(rename = "delivery_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub delivery_id: String,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: EnqueueResponseStatus,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum EnqueueResponseStatus {
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "delivering")]
    Delivering,
    #[serde(rename = "delivered")]
    Delivered,
    #[serde(rename = "retry_scheduled")]
    RetryScheduled,
    #[serde(rename = "dead_letter")]
    DeadLetter,
}

#[derive(Clone, Debug, PartialEq)]
pub enum EnqueueError {
    Forbidden,
    IdempotencyConflict,
    InvalidEvent,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct OutboundWebhook;
impl RequestCapability for OutboundWebhook {
    type Request = EnqueueRequest;
    type Response = EnqueueResponse;
    type DomainError = EnqueueError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != ENQUEUE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OutboundWebhookRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).enqueue(context, request)
    }
}

impl serde::Serialize for EnqueueError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidEvent => serializer.serialize_str("invalid_event"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for EnqueueError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_event" => Ok(Self::InvalidEvent),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_enqueue_request(value: &EnqueueRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_enqueue_request(wire: &str) -> Result<EnqueueRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_enqueue_response(value: &EnqueueResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_enqueue_response(wire: &str) -> Result<EnqueueResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_enqueue_error(value: &EnqueueError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_enqueue_error(wire: &str) -> Result<EnqueueError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoOutboundWebhookEnqueueResult {
    fn __lenso_into_result(self) -> Result<Result<EnqueueResponse, EnqueueError>, RuntimeFailure>;
}
impl __LensoIntoOutboundWebhookEnqueueResult for Result<EnqueueResponse, EnqueueError> {
    fn __lenso_into_result(self) -> Result<Result<EnqueueResponse, EnqueueError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOutboundWebhookEnqueueResult for Result<Result<EnqueueResponse, EnqueueError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<EnqueueResponse, EnqueueError>, RuntimeFailure> { self }
}
impl __LensoIntoOutboundWebhookEnqueueResult for Result<EnqueueResponse, lenso_plugin_authoring::PluginError<EnqueueError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<EnqueueResponse, EnqueueError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOutboundWebhookEnqueueResult for Result<EnqueueResponse, OutboundWebhookInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<EnqueueResponse, EnqueueError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OutboundWebhookInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OutboundWebhookInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait OutboundWebhookProvider: fmt::Debug + 'static {
    fn enqueue(&self, context: InvocationContext, request: EnqueueRequest) -> NativeRequestFuture<OutboundWebhook>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_outbound_webhook {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportOutboundWebhook;
        impl $crate::OutboundWebhookProvider for $plugin {
        fn enqueue(&self, context: __LensoNativeSupportOutboundWebhook::InvocationContext, request: $crate::EnqueueRequest) -> __LensoNativeSupportOutboundWebhook::NativeRequestFuture<$crate::OutboundWebhook> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::enqueue(&plugin, context, request).await;
                $crate::__LensoIntoOutboundWebhookEnqueueResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct OutboundWebhookRequestEndpoint { provider: Rc<dyn OutboundWebhookProvider> }

#[derive(Debug)]
pub struct OutboundWebhookEndpoint<P: OutboundWebhookProvider> { provider: Rc<P>, request_endpoint: OutboundWebhookRequestEndpoint }
impl<P: OutboundWebhookProvider> OutboundWebhookEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn OutboundWebhookProvider> = provider.clone();
        Self { provider, request_endpoint: OutboundWebhookRequestEndpoint { provider: request_provider } }
    }
}

impl<P: OutboundWebhookProvider> NativeRequestEndpoint for OutboundWebhookEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        ENQUEUE_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            ENQUEUE_OPERATION => {
                let Ok(request) = request.downcast::<EnqueueRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).enqueue(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_outbound_webhook {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::OutboundWebhookEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_outbound_webhook {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_outbound_webhook!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct OutboundWebhookClient {
    enqueue: NativeRequestHandle<OutboundWebhook>,
}
impl OutboundWebhookClient {
    pub fn new(handle: NativeRequestHandle<OutboundWebhook>) -> Self {
        Self { enqueue: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn enqueue(&self, request: EnqueueRequest) -> Result<EnqueueResponse, OutboundWebhookInvocationError> {
        self.enqueue.invoke(ENQUEUE_OPERATION, request).await
            .map_err(OutboundWebhookInvocationError::Runtime)?
            .map_err(OutboundWebhookInvocationError::Domain)
    }

    pub async fn enqueue_with_context(&self, context: InvocationContext, request: EnqueueRequest) -> Result<EnqueueResponse, OutboundWebhookInvocationError> {
        self.enqueue.invoke_with_context(ENQUEUE_OPERATION, context, request).await
            .map_err(OutboundWebhookInvocationError::Runtime)?
            .map_err(OutboundWebhookInvocationError::Domain)
    }
}

impl CapabilityClient for OutboundWebhookClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            enqueue: dependencies.one::<OutboundWebhook>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for OutboundWebhookClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    enqueue: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OutboundWebhook>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum OutboundWebhookInvocationError {
    Domain(EnqueueError),
    Runtime(RuntimeFailure),
}
