// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.outbound-webhook-admin@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const OUTBOUND_WEBHOOK_ADMIN_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const OUTBOUND_WEBHOOK_ADMIN_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_outbound_webhook_admin { () => { "{\"capability_id\":\"lenso.outbound-webhook-admin@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"dispatch\",\"inspect\",\"replay\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_outbound_webhook_admin_client { () => { "{\"capability_id\":\"lenso.outbound-webhook-admin@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_outbound_webhook_admin_client { () => { "{\"capability_id\":\"lenso.outbound-webhook-admin@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const DISPATCH_OPERATION: &str = "dispatch";
pub const INSPECT_OPERATION: &str = "inspect";
pub const REPLAY_OPERATION: &str = "replay";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DispatchRequest {

}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DispatchResponse {
    #[serde(rename = "delivery_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub delivery_id: Option<String>,
    #[serde(rename = "outcome")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub outcome: DispatchResponseOutcome,
    #[serde(rename = "receipt")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub receipt: Option<DispatchResponseReceipt>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum DispatchResponseOutcome {
    #[serde(rename = "idle")]
    Idle,
    #[serde(rename = "delivered")]
    Delivered,
    #[serde(rename = "retry_scheduled")]
    RetryScheduled,
    #[serde(rename = "dead_lettered")]
    DeadLettered,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DispatchResponseReceipt {
    #[serde(rename = "attempt")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attempt: i64,
    #[serde(rename = "http_status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub http_status: Option<String>,
    #[serde(rename = "occurred_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub occurred_at: Timestamp,
    #[serde(rename = "outcome")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub outcome: String,
    #[serde(rename = "response_sha256")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub response_sha256: Option<String>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum DispatchError {
    Forbidden,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct InspectRequest {
    #[serde(rename = "delivery_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub delivery_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct InspectResponse {
    #[serde(rename = "attempts")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attempts: i64,
    #[serde(rename = "delivery_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub delivery_id: String,
    #[serde(rename = "endpoint_origin")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub endpoint_origin: String,
    #[serde(rename = "event_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub event_id: String,
    #[serde(rename = "event_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub event_type: String,
    #[serde(rename = "last_receipt")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub last_receipt: Option<InspectResponseLastReceipt>,
    #[serde(rename = "max_attempts")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub max_attempts: i64,
    #[serde(rename = "payload_sha256")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub payload_sha256: String,
    #[serde(rename = "replay_count")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub replay_count: i64,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: InspectResponseStatus,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct InspectResponseLastReceipt {
    #[serde(rename = "attempt")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attempt: i64,
    #[serde(rename = "http_status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub http_status: Option<String>,
    #[serde(rename = "occurred_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub occurred_at: Timestamp,
    #[serde(rename = "outcome")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub outcome: String,
    #[serde(rename = "response_sha256")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub response_sha256: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum InspectResponseStatus {
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "delivering")]
    Delivering,
    #[serde(rename = "retry_scheduled")]
    RetryScheduled,
    #[serde(rename = "delivered")]
    Delivered,
    #[serde(rename = "dead_letter")]
    DeadLetter,
}

#[derive(Clone, Debug, PartialEq)]
pub enum InspectError {
    Forbidden,
    InvalidDelivery,
    NotFound,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReplayRequest {
    #[serde(rename = "delivery_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub delivery_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReplayResponse {
    #[serde(rename = "replay_count")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub replay_count: i64,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReplayError {
    Forbidden,
    InvalidDelivery,
    NotDeadLetter,
    NotFound,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct OutboundWebhookAdminDispatch;
impl RequestCapability for OutboundWebhookAdminDispatch {
    type Request = DispatchRequest;
    type Response = DispatchResponse;
    type DomainError = DispatchError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != DISPATCH_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OutboundWebhookAdminRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).dispatch(context, request)
    }
}

#[derive(Debug)]
pub struct OutboundWebhookAdminInspect;
impl RequestCapability for OutboundWebhookAdminInspect {
    type Request = InspectRequest;
    type Response = InspectResponse;
    type DomainError = InspectError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != INSPECT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OutboundWebhookAdminRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).inspect(context, request)
    }
}

#[derive(Debug)]
pub struct OutboundWebhookAdminReplay;
impl RequestCapability for OutboundWebhookAdminReplay {
    type Request = ReplayRequest;
    type Response = ReplayResponse;
    type DomainError = ReplayError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != REPLAY_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OutboundWebhookAdminRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).replay(context, request)
    }
}

impl serde::Serialize for DispatchError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for DispatchError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for InspectError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidDelivery => serializer.serialize_str("invalid_delivery"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for InspectError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_delivery" => Ok(Self::InvalidDelivery),
                "not_found" => Ok(Self::NotFound),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ReplayError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidDelivery => serializer.serialize_str("invalid_delivery"),
            Self::NotDeadLetter => serializer.serialize_str("not_dead_letter"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReplayError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_delivery" => Ok(Self::InvalidDelivery),
                "not_dead_letter" => Ok(Self::NotDeadLetter),
                "not_found" => Ok(Self::NotFound),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_dispatch_request(value: &DispatchRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_dispatch_request(wire: &str) -> Result<DispatchRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_dispatch_response(value: &DispatchResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_dispatch_response(wire: &str) -> Result<DispatchResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_dispatch_error(value: &DispatchError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_dispatch_error(wire: &str) -> Result<DispatchError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_inspect_request(value: &InspectRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_inspect_request(wire: &str) -> Result<InspectRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_inspect_response(value: &InspectResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_inspect_response(wire: &str) -> Result<InspectResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_inspect_error(value: &InspectError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_inspect_error(wire: &str) -> Result<InspectError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_replay_request(value: &ReplayRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_replay_request(wire: &str) -> Result<ReplayRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_replay_response(value: &ReplayResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_replay_response(wire: &str) -> Result<ReplayResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_replay_error(value: &ReplayError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_replay_error(wire: &str) -> Result<ReplayError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoOutboundWebhookAdminDispatchResult {
    fn __lenso_into_result(self) -> Result<Result<DispatchResponse, DispatchError>, RuntimeFailure>;
}
impl __LensoIntoOutboundWebhookAdminDispatchResult for Result<DispatchResponse, DispatchError> {
    fn __lenso_into_result(self) -> Result<Result<DispatchResponse, DispatchError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOutboundWebhookAdminDispatchResult for Result<Result<DispatchResponse, DispatchError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<DispatchResponse, DispatchError>, RuntimeFailure> { self }
}
impl __LensoIntoOutboundWebhookAdminDispatchResult for Result<DispatchResponse, lenso_plugin_authoring::PluginError<DispatchError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<DispatchResponse, DispatchError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOutboundWebhookAdminDispatchResult for Result<DispatchResponse, OutboundWebhookAdminDispatchInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<DispatchResponse, DispatchError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OutboundWebhookAdminDispatchInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OutboundWebhookAdminDispatchInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoOutboundWebhookAdminInspectResult {
    fn __lenso_into_result(self) -> Result<Result<InspectResponse, InspectError>, RuntimeFailure>;
}
impl __LensoIntoOutboundWebhookAdminInspectResult for Result<InspectResponse, InspectError> {
    fn __lenso_into_result(self) -> Result<Result<InspectResponse, InspectError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOutboundWebhookAdminInspectResult for Result<Result<InspectResponse, InspectError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<InspectResponse, InspectError>, RuntimeFailure> { self }
}
impl __LensoIntoOutboundWebhookAdminInspectResult for Result<InspectResponse, lenso_plugin_authoring::PluginError<InspectError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<InspectResponse, InspectError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOutboundWebhookAdminInspectResult for Result<InspectResponse, OutboundWebhookAdminInspectInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<InspectResponse, InspectError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OutboundWebhookAdminInspectInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OutboundWebhookAdminInspectInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoOutboundWebhookAdminReplayResult {
    fn __lenso_into_result(self) -> Result<Result<ReplayResponse, ReplayError>, RuntimeFailure>;
}
impl __LensoIntoOutboundWebhookAdminReplayResult for Result<ReplayResponse, ReplayError> {
    fn __lenso_into_result(self) -> Result<Result<ReplayResponse, ReplayError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOutboundWebhookAdminReplayResult for Result<Result<ReplayResponse, ReplayError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ReplayResponse, ReplayError>, RuntimeFailure> { self }
}
impl __LensoIntoOutboundWebhookAdminReplayResult for Result<ReplayResponse, lenso_plugin_authoring::PluginError<ReplayError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ReplayResponse, ReplayError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOutboundWebhookAdminReplayResult for Result<ReplayResponse, OutboundWebhookAdminReplayInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ReplayResponse, ReplayError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OutboundWebhookAdminReplayInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OutboundWebhookAdminReplayInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait OutboundWebhookAdminProvider: fmt::Debug + 'static {
    fn dispatch(&self, context: InvocationContext, request: DispatchRequest) -> NativeRequestFuture<OutboundWebhookAdminDispatch>;
    fn inspect(&self, context: InvocationContext, request: InspectRequest) -> NativeRequestFuture<OutboundWebhookAdminInspect>;
    fn replay(&self, context: InvocationContext, request: ReplayRequest) -> NativeRequestFuture<OutboundWebhookAdminReplay>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_outbound_webhook_admin {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportOutboundWebhookAdmin;
        impl $crate::OutboundWebhookAdminProvider for $plugin {
        fn dispatch(&self, context: __LensoNativeSupportOutboundWebhookAdmin::InvocationContext, request: $crate::DispatchRequest) -> __LensoNativeSupportOutboundWebhookAdmin::NativeRequestFuture<$crate::OutboundWebhookAdminDispatch> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::dispatch(&plugin, context, request).await;
                $crate::__LensoIntoOutboundWebhookAdminDispatchResult::__lenso_into_result(result)
            })
        }
        fn inspect(&self, context: __LensoNativeSupportOutboundWebhookAdmin::InvocationContext, request: $crate::InspectRequest) -> __LensoNativeSupportOutboundWebhookAdmin::NativeRequestFuture<$crate::OutboundWebhookAdminInspect> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::inspect(&plugin, context, request).await;
                $crate::__LensoIntoOutboundWebhookAdminInspectResult::__lenso_into_result(result)
            })
        }
        fn replay(&self, context: __LensoNativeSupportOutboundWebhookAdmin::InvocationContext, request: $crate::ReplayRequest) -> __LensoNativeSupportOutboundWebhookAdmin::NativeRequestFuture<$crate::OutboundWebhookAdminReplay> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::replay(&plugin, context, request).await;
                $crate::__LensoIntoOutboundWebhookAdminReplayResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct OutboundWebhookAdminRequestEndpoint { provider: Rc<dyn OutboundWebhookAdminProvider> }

#[derive(Debug)]
pub struct OutboundWebhookAdminEndpoint<P: OutboundWebhookAdminProvider> { provider: Rc<P>, request_endpoint: OutboundWebhookAdminRequestEndpoint }
impl<P: OutboundWebhookAdminProvider> OutboundWebhookAdminEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn OutboundWebhookAdminProvider> = provider.clone();
        Self { provider, request_endpoint: OutboundWebhookAdminRequestEndpoint { provider: request_provider } }
    }
}

impl<P: OutboundWebhookAdminProvider> NativeRequestEndpoint for OutboundWebhookAdminEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        DISPATCH_OPERATION,
        INSPECT_OPERATION,
        REPLAY_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            DISPATCH_OPERATION => {
                let Ok(request) = request.downcast::<DispatchRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).dispatch(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            INSPECT_OPERATION => {
                let Ok(request) = request.downcast::<InspectRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).inspect(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            REPLAY_OPERATION => {
                let Ok(request) = request.downcast::<ReplayRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).replay(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_outbound_webhook_admin {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::OutboundWebhookAdminEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_outbound_webhook_admin {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_outbound_webhook_admin!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct OutboundWebhookAdminClient {
    dispatch: NativeRequestHandle<OutboundWebhookAdminDispatch>,
    inspect: NativeRequestHandle<OutboundWebhookAdminInspect>,
    replay: NativeRequestHandle<OutboundWebhookAdminReplay>,
}
impl OutboundWebhookAdminClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn dispatch(&self, request: DispatchRequest) -> Result<DispatchResponse, OutboundWebhookAdminDispatchInvocationError> {
        self.dispatch.invoke(DISPATCH_OPERATION, request).await
            .map_err(OutboundWebhookAdminDispatchInvocationError::Runtime)?
            .map_err(OutboundWebhookAdminDispatchInvocationError::Domain)
    }

    pub async fn dispatch_with_context(&self, context: InvocationContext, request: DispatchRequest) -> Result<DispatchResponse, OutboundWebhookAdminDispatchInvocationError> {
        self.dispatch.invoke_with_context(DISPATCH_OPERATION, context, request).await
            .map_err(OutboundWebhookAdminDispatchInvocationError::Runtime)?
            .map_err(OutboundWebhookAdminDispatchInvocationError::Domain)
    }

    pub async fn inspect(&self, request: InspectRequest) -> Result<InspectResponse, OutboundWebhookAdminInspectInvocationError> {
        self.inspect.invoke(INSPECT_OPERATION, request).await
            .map_err(OutboundWebhookAdminInspectInvocationError::Runtime)?
            .map_err(OutboundWebhookAdminInspectInvocationError::Domain)
    }

    pub async fn inspect_with_context(&self, context: InvocationContext, request: InspectRequest) -> Result<InspectResponse, OutboundWebhookAdminInspectInvocationError> {
        self.inspect.invoke_with_context(INSPECT_OPERATION, context, request).await
            .map_err(OutboundWebhookAdminInspectInvocationError::Runtime)?
            .map_err(OutboundWebhookAdminInspectInvocationError::Domain)
    }

    pub async fn replay(&self, request: ReplayRequest) -> Result<ReplayResponse, OutboundWebhookAdminReplayInvocationError> {
        self.replay.invoke(REPLAY_OPERATION, request).await
            .map_err(OutboundWebhookAdminReplayInvocationError::Runtime)?
            .map_err(OutboundWebhookAdminReplayInvocationError::Domain)
    }

    pub async fn replay_with_context(&self, context: InvocationContext, request: ReplayRequest) -> Result<ReplayResponse, OutboundWebhookAdminReplayInvocationError> {
        self.replay.invoke_with_context(REPLAY_OPERATION, context, request).await
            .map_err(OutboundWebhookAdminReplayInvocationError::Runtime)?
            .map_err(OutboundWebhookAdminReplayInvocationError::Domain)
    }
}

impl CapabilityClient for OutboundWebhookAdminClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            dispatch: dependencies.one::<OutboundWebhookAdminDispatch>()?,
            inspect: dependencies.one::<OutboundWebhookAdminInspect>()?,
            replay: dependencies.one::<OutboundWebhookAdminReplay>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for OutboundWebhookAdminClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    dispatch: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OutboundWebhookAdminDispatch>()?,
                    inspect: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OutboundWebhookAdminInspect>()?,
                    replay: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OutboundWebhookAdminReplay>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum OutboundWebhookAdminDispatchInvocationError {
    Domain(DispatchError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum OutboundWebhookAdminInspectInvocationError {
    Domain(InspectError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum OutboundWebhookAdminReplayInvocationError {
    Domain(ReplayError),
    Runtime(RuntimeFailure),
}
